export const disciplines = [
  "salud/estética",
  "fútbol",
  "tenis",
  "rugby",
  "básquet",
  "vóley",
  "running",
  "ciclismo ruta",
  "mountain bike",
  "natación",
  "atletismo velocidad",
  "artes marciales",
  "atletismo lanzamientos",
  "fisicoculturismo",
  "gimnasia deportiva",
  "hándbol",
  "judo",
  "patín artístico",
  "patín carrera",
  "hockey",
  "snowboard",
  "béisbol",
  "tenis de mesa",
  "golf",
  "surf",
  "squash",
  "pádel",
  "softball",
  "atletismo salto",
];
